### PR TITLE
Featured storybook users

### PR DESCRIPTION
**Pull request by shilman**
Issue: #56

storybook_-_ui_dev_environment_you_ll_love_to_use

## What I did

- collected some logos
- created a new component UsedBy with @SachaG 
- added to homepage
- added a story to the storybook

## How to test
```
npm install
npm run storybook # test in storybook
npm run develop # test in gatsby
```

### CODE REVIEW

**Comment by shilman** [comment]
cc @sachag

**Comment by apexskier** [comment]
Here's an SVG of the Remitly logo:

[logo-horizontal-blue_161e8a0f5e69186b6ecb3e3d122e92ad.svg.zip](https://github.com/storybooks/storybooks.github.io/files/1026374/logo-horizontal-blue_161e8a0f5e69186b6ecb3e3d122e92ad.svg.zip)

**Comment by sibelius** [comment]
Wix is using storybook as well

https://wix.github.io/wix-style-react/

**Comment by shilman** [comment]
Thanks @apexskier @sibelius ! Updated the list!

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
